site_name: Privacy Fingerprint
repo_url: https://github.com/nhsengland/privfp-experiments
repo_name: privfp-experiments

nav:
  - Home: index.md
  - Background: background.md
  - Setup:
    - setup/index.md
    - 1. HomeBrew Installation: setup/homebrew-install.md
    - 2. Julia Installation: setup/julia-install.md
    - 3. Environment Set-up: setup/environment-setup.md
    - 4. Setting up Synthea International: setup/synthea.md
    - 5. Install Ollama and set-up Large Language Models: setup/llm.md
    - 6. Install UniversalNER Locally: setup/extraction.md

  - Open source LLM exploration:
    - open-source-llm-exploration/index.md
    - Searching for open source LLMs: open-source-llm-exploration/search.md
    - Setting up open source LLMs: open-source-llm-exploration/setup.md
    - Running inference: open-source-llm-exploration/inference.md
    - Evaluating generated outputs: open-source-llm-exploration/evaluation.md
    - Metrics to assess the quality of generated outputs: open-source-llm-exploration/metrics.md

  - Open source extraction exploration:
    - open-source-extraction-exploration/index.md
    - Open-source Named-Entity Recognition Models: open-source-extraction-exploration/named_entity_research.md
    - De-identification Methods: open-source-extraction-exploration/deidentification_research.md

  - (Py)Correct Match (Scorer Component):
    - correct-match/index.md
    - What is Correct Match?: correct-match/what-is-correct-match.md
    - How does Correct Match Work?: correct-match/how-correct-match-works.md

  - SHAP(Explainer Component):
    - shap-explainer/index.md
    - What is SHAP and Why use it?: shap-explainer/what-is-shap-and-why-use-it.md
    - How does SHAP Work and can be Applied?: shap-explainer/how-does-shap-work-and-be-applied.md
    - Additional Resources: shap-explainer/additional-reads.md


theme:
  name: material
  custom_dir: overrides

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - header.autohide
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nhsengland

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html

  - pymdownx.details
  - pymdownx.superfences

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji # yamllint disable-line
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - enumerate-headings:
      toc_depth: 2
      restart_increment_after:
        - "*index.md"
      exclude:
        - index.md
        - background.md

watch:
  - overrides
