
output_paths:
  output_folder: ../outputs
  extraction_template: ../templates/extraction/
  generate_template: ../templates/generate/
  synthea_prefix: synthea
  generate_prefix: generate
  extraction_prefix: extraction
  standardise_prefix: standardise

synthea:
  path_synthea: ../../synthea
