name: documentation

on:
  push:
    branches:
      - main

    paths:
      - 'mkdocs.yml'
      - 'docs/**'
      - 'overrides/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_docs.txt

      - name: Build and deploy documentation
        run: |
          mkdocs gh-deploy
