# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Python Setup

on: [push, pull_request]

env:
    PYTHON_VERSION: 3.11.7

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: ${{env.PYTHON_VERSION}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Install pre-commit and dependencies
      run: |
        python -m pip install pre-commit jupyter

    - name: Install Pre-commit hooks
      run: pre-commit install

    - name: Run pre-commit
      run: pre-commit run --all-files
