# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Python Setup

on: [push, pull_request]

env:
    BLACK_VERSION: 23.12.1
    PYTHON_VERSION: 3.11.6

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: ${{env.PYTHON_VERSION}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python${{env.PYTHON_VERSION}} -m pip install -r requirements.txt
    - name: Install Linting Dependences
      run: |
        python${{env.PYTHON_VERSION}} -m  pip install black==${{env.BLACK_VERSION}}
        python${{env.PYTHON_VERSION}} -m  pip install flake8

    - name: Lint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src --max-line-length=127
        black --check *.py
